#! /bin/sh
set -e

# Based on:
#   http://thorstenl.blogspot.com/2007/01/thls-irssi-notification-script.html


# -----------------------------------------------------------------------------------
# First of all, let's retrieve existing unread messages

tmpfilename=`mktemp`
ssh -n user@77.221.148.122 'tail -n 10 ~/.irssi/fnotify' > $tmpfilename

linecnt=`wc -l $tmpfilename | awk '{print $1}'`
while [ $linecnt -ge 1 ]
do

   tmpfilename_part=`mktemp`
   cat $tmpfilename | \
      sed -n "$linecnt"p | \
      sed -u 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/\\/\\\\/g' \
      > $tmpfilename_part

   while read heading message; do
      if [ "${heading}" != "---dehighlight---" ]; then
         echo "existing unread message: ${heading} --- ${message}"
         notify-send -i gtk-dialog-info -t 10000 -- "${heading}" "${message}"
         play -q /home/dimon/irssi-notify/sounds/message.wav &
         /home/dimon/irssi-notify/irssi-tray.pl &
      else
         echo "no more unread messages"
         break 2
      fi
   done < $tmpfilename_part
   rm $tmpfilename_part
   linecnt=$(($linecnt - 1))
done
      
rm $tmpfilename



# -----------------------------------------------------------------------------------
# Now, listen for new messages

echo "listening for new messages.."

ssh -n user@77.221.148.122 'tail -n 0 -f ~/.irssi/fnotify' | \
	sed -u 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/\\/\\\\/g' | \
   while read heading message; do
      if [ "${heading}" != "---dehighlight---" ]; then
         notify-send -i gtk-dialog-info -t 10000 -- "${heading}" "${message}"
         play -q /home/dimon/irssi-notify/sounds/message.wav &
         /home/dimon/irssi-notify/irssi-tray.pl &
      else
         killall irssi-tray.pl &
      fi
   done

